Release v1.1.0
Kaholo/kaholo-plugin-xray pull request #7
Opened 2022-08-24 08:43 UTC by xkcm

Added:
* [**KP-872**](https://kaholo.atlassian.net/browse/KP-872) "Import Cucumber JSON Execution Results" method
* [**KP-872**](https://kaholo.atlassian.net/browse/KP-872) "Import Junit XML Execution Results" method
* [**KP-874**](https://kaholo.atlassian.net/browse/KP-874)  "Create Execution Result" method

2022-08-24 11:13 UTC, graddaniel submitted a review, later dismissed

2022-08-24 17:33 UTC, kenskyfish submitted a review, later dismissed
Tested, working well.

2022-08-25 11:54 UTC, kenskyfish approved these changes

2022-08-31 10:31 UTC, kenskyfish requested changes
Merge documentation update before release please.

2022-09-06 22:19 UTC, kenskyfish approved these changes, later dismissed
Tested Working well

2022-09-08 10:56 UTC, graddaniel approved these changes

2022-09-08 11:21 UTC, Kszemi approved these changes

2022-09-09 13:09 UTC, merged